#
# MySQL environment on docker
#

version: '3'

services:
  play-scala:
    image: hseeberger/scala-sbt:8u242_1.3.8_2.13.1
    container_name: playscala_todo
    ports:
      - "9000:9000"
    volumes:
      - .:/source
      - ./.ivy2:/root/.ivy2
      - ./.sbt:/root/.sbt
      - ./.cache:/root/.cache
    working_dir: /source
    tty: true
    networks:
      - app-net

  # MySQL
  db:
    image: mysql:5.7
    container_name: todo_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE:      to_do
      MYSQL_USER:          docker
      MYSQL_PASSWORD:      docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 33306:3306
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
